---
- name: Create instance on openstack
  os_server:
    state: present
    name: "{{ instance_name }}"
    image: Ubuntu server 20.04
    availability_zone: Education
    flavor: "{{ instance_flavor }}"
    key_name: "{{ instance_key_name }}"
    auto_ip: no
    security_groups: "{{ instance_security_groups }}"
  register: instance

- name: Add instance to inventory
  add_host:
    name: "{{ instance_name }}"
    ansible_host: "{{ instance.openstack.private_v4 }}"
    ansible_user: ubuntu
    public_host: "{{ instance.openstack.accessIPv4 }}"