---
- name: Create OpenStack instance
  os_server:
    state: present
    name: wordpress1 #Duplicate_1
    image: Ubuntu server 20.04
    availability_zone: Education
    flavor: c1-r1-d10
    key_name: ansible_key
    auto_ip: no
    security_groups: default,SSH,HTTP
  register: wordpress1 #Duplicate_1

- name: Add wordpress1 to inventory
  add_host:
    name: wordpress1 #Duplicate_1
    ansible_host: "{{ wordpress1.openstack.private_v4 }}"
    ansible_user: ubuntu

- name: Create OpenStack instance
  os_server:
    state: present
    name: wordpress2 #Duplicate_2
    image: Ubuntu server 20.04
    availability_zone: Education
    flavor: c1-r1-d10
    key_name: ansible_key
    auto_ip: no
    security_groups: default,SSH,HTTP
  register: wordpress2 #Duplicate_2

- name: Add wordpress2 to inventory
  add_host:
    name: wordpress2 #Duplicate_2
    ansible_host: "{{ wordpress2.openstack.private_v4 }}"
    ansible_user: ubuntu
