---
  - name: Create OpenStack NGINX Uploads instance
    os_server:
      state: present
      name: nginx_wpuploads
      image: Ubuntu server 20.04
      availability_zone: Education
      flavor: c1-r1-d10
      key_name: Marcus
      security_groups: default,SSH,HTTP
    register: nginx_wpuploads

  - name: Add to inventory
    add_host:
      name: nginx_wpuploads
      ansible_host: "{{ nginx_wpuploads.openstack.accessIPv4 }}"
      ansible_user: ubuntu
