---
- name: Create security groups on openstack
  hosts: localhost

  tasks:
    - name: Create a security group for SSH
      os_security_group:
        name: SSH
        state: present
    
    - name: Add rule to the SSH security group
      os_security_group_rule:
        security_group: SSH
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
