---
- name: Create initial infrastructure on openstack
  hosts: localhost
  roles:
    - initial_infrastructure_openstack_create
    
  tasks:  
    - name: Wait for interface to attach
      pause:
        seconds: 60

- name: Create security groups
  hosts: localhost
  roles:
    - role: security_groups_openstack_create
      vars:
        security_group_name: SSH
        security_group_port: 22
    - role: security_groups_openstack_create
      vars:
        security_group_name: HTTP
        security_group_port: 80
    - role: security_groups_openstack_create
      vars:
        security_group_name: MySQL
        security_group_port: 3306
    - role: security_groups_openstack_create
      vars:
        security_group_name: Monitor
        security_group_port: 9100
    - role: security_groups_openstack_create
      vars:
        security_group_name: Grafana
        security_group_port: 3000    

  tasks:  
    - name: Wait for security groups
      pause:
        seconds: 20

- name: Create instance for Ansible
  hosts: localhost
  roles:
    - role: instance_public_openstack_create
      vars:
        instance_name: ansible
        instance_flavor: c4-r8-d80
        instance_key_name: cscloud-oh222fv
        instance_security_groups: default,SSH
        instance_floating_ip: 194.47.176.254 #Set in group_vars
  
  tasks:  
    - name: Wait for SSH to be ready
      pause:
        seconds: 60
    
- name: Install Ansible
  hosts: ansible
  roles:
    - ansible_control_node_install
