---
- name: Create instance for Ansible
  hosts: localhost
  roles:
    - openstack_ansible_create_instance
    
- name: Install Ansible
  hosts: ansible
  roles:
    - openstack_ansible_install
    
