---
- name: Create instance for Ansible
  hosts: localhost
  roles:
    - openstack_ansible_create_instance
  
  tasks:  
    - name: Wait for SSH to be ready
      pause:
        seconds: 60
    
- name: Install Ansible
  hosts: ansible
  roles:
    - openstack_ansible_install
    
