---
  - name: Install MySQL on slave
    become: yes
    apt:
      name: [mysql-server, mysql-client, python3-pymysql]
      state: latest
  
  - name: Copy a MySQL slave .conf file into place, backing up the original if it differs from the copied version
    become: yes
    template:
      src: files/mysqld.cnf.j2
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      owner: root
      group: root
      mode: 0644
      backup: yes
  
  - name: Restarting MySQL
    become: yes
    service:
      name: mysql
      state: restarted
      enabled: yes
  
  - name: Create MySQL user for slave
    become: true
    shell: |
      mysql -u root -p'{{ mysql_root_password }}' -e "STOP SLAVE;"
      mysql -u root -p'{{ mysql_root_password }}' -e "CHANGE MASTER TO MASTER_HOST='{{ hostvars['mysqlmaster']['ansible_host'] }}', MASTER_USER='{{ mysql_replication_user }}', MASTER_PASSWORD='{{ mysql_replication_user_password }}', MASTER_LOG_FILE='{{ hostvars['mysql_master_fileposition']['ansible_mysql_filename'] }}', MASTER_LOG_POS={{ hostvars['mysql_master_fileposition']['ansible_mysql_position'] }};"
      mysql -u root -p'{{ mysql_root_password }}' -e "START SLAVE;"
    
  