---
- name: create a volume
  hosts: localhost
  tasks:

  - name: Create 10 GB volume
    os_volume:
      display_name: "{{ volume_name }}"
      size: 10
      volume_type: rbd
      availability_zone: nova
      state: present

  - name: Attach volume to host
    os_server_volume:
      server: "{{ instance_name }}"
      volume: "{{ volume_name }}"
      device: /dev/vdb
      state: present

- hosts: "{{ instance_ip }}"

  tasks:

    - name: Copy files to instance
      synchronize:
        src: ./volume_files
        dest: /home/ubuntu