---
- name: Ubuntu update 
  become: yes   
  apt:
    update_cache: yes 

- name: Install Ansible #Maybe install Ansible with pip3 instead?
  become: yes
  apt:
    name: ansible
    state: latest
    
- name: Install pip3
  become: yes
  apt:
    name: python3-pip
    state: latest
    
- name: Install Openstack SDK
  become: yes
  shell:
    pip3 install openstacksdk   
    
- name: Clone project repo from github
  git:
    repo: https://github.com/mjovanc/deployment-infrastructures-2DV517.git
    dest: "{{ path_to_ansible_home }}"

- name: Copy clouds.yml to control node  #VARIABLES
  copy:
    src: clouds.yaml
    dest: "{{ path_to_ansible_home }}/clouds.yaml"
    
- name: Generate new SSH keypair on openstack
  os_keypair:
    name: "{{ new_ssh_keyname }}"
