---
- name: Ubuntu update 
  become: yes   
  apt:
    update_cache: yes 

- name: Install Ansible #Maybe install Ansible with pip3 instead?
  become: yes
  apt:
    name: ansible
    state: latest
    
- name: Install pip3
  become: yes
  apt:
    name: python3-pip
    state: latest
    
- name: Install Openstack SDK
  become: yes
  shell:
    pip3 install openstacksdk
    
- name: Generate SSH keypair
  become: yes
  openssh_keypair:
    path: "{{ ssh_path_filename }}"
    type: rsa
    size: 4096
    state: present
    force: no
    
