---
- name: Ubuntu update 
  become: yes   
  apt:
    update_cache: yes 

- name: Install Ansible
  become: yes
  apt:
    name: ansible
    state: latest
    
- name: Install pip3
  become: yes
  apt:
    name: python3-pip
    state: latest
    
- name: Install Openstack SDK
  become: yes
  shell:
    pip3 install openstacksdk
