---
- name: install alertmanager directory
  get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    dest: "{{ home_dir }}"
    checksum: sha256:9ccd863937436fd6bfe650e22521a7f2e6a727540988eef515dde208f9aef232
    remote_src: true

- name: unpack alertmanager directory
  become: yes
  unarchive:
    src: alertmanager-0.21.0.linux-amd64.tar.gz
    dest: "{{ home_dir }}"
    owner: ubuntu
    group: ubuntu
    remote_src: yes

- name: Make sure user is in home directory
  become: yes
  command: bash -lc "cd {{ home_dir }}"

- name: Move alertmanager binary file
  become: yes
  copy:
    src: alertmanager-0.21.0.linux-amd64/alertmanager
    dest: /usr/local/bin
    owner: ubuntu
    group: ubuntu
    remote_src: yes
    mode: +x

- name: Move amtool binary file
  become: yes
  copy:
    src: alertmanager-0.21.0.linux-amd64/amtool
    dest: /usr/local/bin
    owner: ubuntu
    group: ubuntu
    remote_src: yes
    mode: +x

- name: Create /etc/alertmanager directory
  become: yes
  file:
    path: /etc/alertmanager
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Create /data/alertmanager directory
  become: yes
  file:
    path: /data/alertmanager
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Move amlertmanager.yml to /etc/alertmanager/
  become: yes
  copy:
    # Moving a .j2 file from host server to remote server might now work like this?
    src: alertmanager.yml.j2
    # src: alertmanager-0.21.0.linux-amd64/alertmanager.yml
    dest: /etc/alertmanager/
    owner: ubuntu
    group: ubuntu
    remote_src: yes
    mode: +x

- name: Writing alertmanager.service file to systemd
  become: yes
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service
    owner: ubuntu
    group: ubuntu

- name: Make sure user is in bin directory
  become: yes
  command: bash -lc "cd /usr/local/bin/"

- name: Reloading systemctl daemon
  become: yes
  systemd:
    daemon_reload: yes

- name: Starting alertmanager.service
  become: yes
  systemd:
    state: started
    name: alertmanager

- name: Enabling alertmanager.service to start on boot
  become: yes
  systemd:
    enabled: yes
    name: alertmanager

- name: Reloading systemctl daemon
  become: yes
  systemd:
    daemon_reload: yes

- name: Restarting prometheus.service
  become: yes
  systemd:
    state: restarted
    name: prometheus