---
- name: Install and running Node Exporter on remote server
  hosts: local
  become: yes
  # TODO: THE KEY FILE SHOULD BE CHANGED WHEN INTEGRATING
  # -----------------------------------------------------
  vars:
    ansible_ssh_private_key_file: "{{ key1 }}"
  # -----------------------------------------------------
  remote_user: ubuntu
  tasks:
    - name: Make sure user is in home directory
      command: bash -lc "cd {{ home_dir }}"

    - name: Get node_exporter package
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: "{{ home_dir }}"
        checksum: sha256:7ffb3773abb71dd2b2119c5f6a7a0dbca0cff34b24b2ced9e01d9897df61a127
        remote_src: true

    - name: Unpack node_exporter package
      unarchive:
        src: "node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "{{ home_dir }}"
        owner: ubuntu
        group: ubuntu
        remote_src: yes

    - name: Move node_exporter binary
      copy:
        src: node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
        dest: /usr/local/bin
        owner: ubuntu
        group: ubuntu
        remote_src: yes
        mode: +x

    - name: Remove leftover files
      shell: rm -rf node_exporter-{{ node_exporter_version }}.linux-amd64 node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz

    - name: Make sure user is in bin directory
      command: bash -lc "cd /usr/local/bin/"

    - name: Reloading systemctl daemon
      systemd:
        daemon_reload: yes

    - name: Starting node_exporter.service
      systemd:
        state: started
        name: node_exporter

    - name: Enabling node_exporter.service to start on boot
      systemd:
        enabled: yes
        name: node_exporter
