---
- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: latest
    
- name: Place config file
  become: yes
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/sites-available/nginx.conf"

- name: Link config files
  become: yes
  file:
    src: "/etc/nginx/sites-available/nginx.conf"
    dest: "/etc/nginx/sites-enabled/nginx.conf"
    state: link
  notify: Reload Nginx

- name: Removes "default" site
  become: yes
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx
