---
- name: "Create/Delete a security group for {{ security_group_name }}: {{ security_group_state }}"
  os_security_group:
    name: "{{ security_group_name }}"
    state: "{{ security_group_state }}"

- name: Add rule to security group
  os_security_group_rule:
    security_group: "{{ security_group_name }}"
    protocol: tcp
    port_range_min: "{{ security_group_port }}"
    port_range_max: "{{ security_group_port }}"
    remote_ip_prefix: 0.0.0.0/0
  when: security_group_state == "present"
