---
- name: "Attach/Detach volume to host: {{ state }}"
  os_server_volume:
    server: "{{ instance_name }}"
    volume: "{{ volume_name }}"
    device: /dev/sdb
    state: "{{ state }}"
  tags: [ attach-volume ]
